version: '3.9'

name: zenithwork

services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zenithwork
    ports:
      - 5432:5432
    networks:
      - zenithwork
    volumes:
      - zenithwork_db:/var/lib/postgresql/data
  pgadmin4:
    image: elestio/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: 123123
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - '8080:8080'
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - zenithwork

volumes:
  zenithwork_db:

networks:
  zenithwork:
